"use client";

import { BrainCircuit, Quote } from "lucide-react";
import { cn } from "@/lib/utils";

interface SmartInsightProps {
  analysis: string;
  locale: "en" | "ar";
}

export function SmartInsight({ analysis, locale }: SmartInsightProps) {
  return (
    <section className="relative overflow-hidden rounded-[2rem] border bg-primary/5 p-8 md:p-12 lg:p-16">
      {/* Decorative Elements */}
      <div className="absolute right-0 top-0 -z-10 h-32 w-32 translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/20 blur-3xl" />
      <div className="absolute left-0 bottom-0 -z-10 h-32 w-32 -translate-x-1/2 translate-y-1/2 rounded-full bg-primary/10 blur-3xl" />

      <div className="mx-auto max-w-3xl space-y-8">
        <div className="flex items-center justify-center gap-3 text-primary">
          <div className="h-px flex-1 bg-gradient-to-r from-transparent to-primary/30" />
          <div className="rounded-xl bg-primary/10 p-3">
            <BrainCircuit className="h-8 w-8" />
          </div>
          <div className="h-px flex-1 bg-gradient-to-l from-transparent to-primary/30" />
        </div>

        <div className="relative text-center">
          <Quote className={cn(
            "absolute -top-6 h-12 w-12 text-primary/10",
            locale === "en" ? "-left-6" : "-right-6"
          )} />
          
          <h2 className="mb-6 text-2xl font-black md:text-3xl lg:text-4xl">
            {locale === "en" ? "AI Strategic Insight" : "رؤية استراتيجية للذكاء الاصطناعي"}
          </h2>
          
          <p className="text-xl leading-relaxed text-muted-foreground md:text-2xl italic font-medium">
            "{analysis}"
          </p>
        </div>

        <div className="flex items-center justify-center gap-4 pt-4">
          <div className="flex -space-x-2 rtl:space-x-reverse">
             {[1,2,3].map(i => (
               <div key={i} className="h-10 w-10 rounded-full border-2 border-background bg-muted ring-2 ring-primary/20" />
             ))}
          </div>
          <p className="text-sm font-bold text-muted-foreground uppercase tracking-widest">
            {locale === "en" ? "Generated by AI Bridge Core" : "تم التوليد بواسطة محرك AI Bridge"}
          </p>
        </div>
      </div>
    </section>
  );
}
